spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: 123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: trace